/**
 * Team facts: record, schedule, results, next game and rank, from ESPN.
 *
 * WHY THIS EXISTS. A team page (`fan/<id>`) was written by a model with web
 * search, and only when somebody tapped the paid research button. So every
 * fact on it froze the moment it was written: Georgia's page, researched the
 * morning of the Arkansas game, still said 2-0, "next: at Arkansas" and #2 a
 * week later, on the day of the Oklahoma game. Erik: "the uga record is wrong,
 * they beat Arkansas last week".
 *
 * The split that fixes it: FACTS FROM ESPN, PROSE FROM THE MODEL. A record, a
 * score, a kickoff time and a poll position are not opinions; ESPN publishes
 * them for free, keyless, the moment they change. What a model is for is the
 * storyline, and that is shown with the date it was written and a note when a
 * game has been played since.
 *
 * THE SOURCE. The same unofficial family as live.js (site.web.api.espn.com,
 * falling back to site.api on a 403 - see ESPN_HOST there):
 *   - /teams/{espnId}/schedule?season=YYYY  - a team's games and results
 *   - /rankings                              - the AP Top 25 (and others, ignored)
 * Keyless, undocumented, able to change shape without notice. So every field
 * is picked out by name through live.js's own cleaners, bounded, stripped of
 * markup, and the page escapes it all again. Any failure falls back to the
 * last good facts (memory, then Firestore), and then to the model's page as it
 * was - never a 500, never a blank tab.
 *
 * WHICH ESPN TEAM. teams.js ids map to ESPN ids through `espn-ids.js`, a
 * static file generated by `node teamfacts.js --ids <teams.json>` from ESPN's
 * team list (see the bottom of this file). Static because a team's ESPN id
 * does not change and a lookup per cold instance buys nothing. And checked on
 * every fetch: a schedule whose own team does not resolve back to the teams.js
 * id we asked for is refused, so one wrong id in that file shows nothing
 * rather than someone else's season.
 *
 * BILLED PER REQUEST. No timers. The cache (30 min in memory, the same in
 * Firestore so a cold instance does not refetch) is filled by whichever
 * request finds it stale, inside that request.
 *
 * No model call anywhere in here.
 */

const teams = require('./teams');
const live = require('./live');
const { ESPN_IDS, UNMAPPED } = require('./espn-ids');

const { str, int, isoOrEmpty, gameState, obj, arr } = live;

const ESPN_BASE = `${live.ESPN_HOST}/apis/site/v2/sports/football/college-football`;
const TEAMS_URL = `${ESPN_BASE}/teams?groups=80&limit=500`;
const RANKINGS_URL = `${ESPN_BASE}/rankings`;
const scheduleUrl = (espnId, season) => `${ESPN_BASE}/teams/${encodeURIComponent(espnId)}/schedule?season=${season}`;

const TTL_MS = 30 * 60 * 1000;
// A failed fetch is remembered this long, so ESPN being down costs one attempt
// per team per two minutes rather than one per view.
const FAIL_TTL_MS = 2 * 60 * 1000;
const FETCH_TIMEOUT_MS = 6000;
const MAX_BYTES = 3 * 1024 * 1024;
const MAX_EVENTS = 20;
// How long after kickoff a game is assumed to be over, for "was this storyline
// written before that game ended".
const GAME_LENGTH_MS = 4 * 3600 * 1000;

const ESPN_TO_TEAM = new Map(Object.entries(ESPN_IDS).map(([id, espn]) => [espn, id]));

function espnIdFor(teamId) {
  const id = teams.validId(teamId);
  return id ? ESPN_IDS[id] || null : null;
}

/** The season a date belongs to. January is still last season's bowls. */
function seasonFor(nowMs) {
  const d = new Date(nowMs);
  return d.getUTCMonth() === 0 ? d.getUTCFullYear() - 1 : d.getUTCFullYear();
}

const ET = 'America/New_York';
const fmt = (opts) => new Intl.DateTimeFormat('en-US', { timeZone: ET, ...opts });
const WK_FMT = fmt({ month: 'short', day: 'numeric' });
const DAY_FMT = fmt({ weekday: 'short' });
const DATE_FMT = fmt({ weekday: 'short', month: 'short', day: 'numeric' });
const TIME_FMT = fmt({ hour: 'numeric', minute: '2-digit' });

/** "Sat 7:30 PM ET", or "Sat, Nov 7 · time TBA" when ESPN has no time yet. */
function kickoffLabel(iso, timeValid) {
  const t = Date.parse(iso);
  if (!Number.isFinite(t)) return '';
  if (!timeValid) return `${DATE_FMT.format(t)} · time TBA`;
  return `${DAY_FMT.format(t)} ${TIME_FMT.format(t)} ET`;
}

/* ------------------------------------------------------------------ *
 * Names
 * ------------------------------------------------------------------ */

/** An ESPN team object -> { espnId, teamId, name }. A team we know is named
 *  the way the rest of the app names it; anyone else (an FCS opponent) by the
 *  feed's own name, cleaned. */
function espnTeam(raw) {
  const t = obj(raw);
  const espnId = str(t.id, 12);
  const fields = {
    displayName: str(t.displayName, 60), location: str(t.location, 60),
    shortDisplayName: str(t.shortDisplayName, 60), name: str(t.name, 40),
  };
  const byName = live.resolveEspnTeam(fields);
  const byId = ESPN_TO_TEAM.get(espnId) || null;
  // Both must agree when both answer; a disagreement is nobody.
  const teamId = byId && byName && byId !== byName ? null : (byId || byName);
  const meta = teamId ? teams.get(teamId) : null;
  return {
    espnId: /^\d{1,8}$/.test(espnId) ? espnId : '',
    teamId,
    name: meta ? meta.name : (fields.location || fields.shortDisplayName || fields.displayName || 'TBD'),
  };
}

/** "at Arkansas" / "vs Florida (Atlanta)" / "#24 Oklahoma" -> a teams.js id. */
function oppTeamId(text) {
  const s = String(text || '')
    .replace(/\([^)]*\)/g, ' ')
    .replace(/^\s*(at|@|vs\.?|v\.?)\s+/i, '');
  return live.resolveTeam(s);
}

/* ------------------------------------------------------------------ *
 * The team list -> the id map (used to generate espn-ids.js)
 * ------------------------------------------------------------------ */

/** ESPN's /teams response -> { map: {teamId: espnId}, missing, unmatched, conflicts }. */
function buildEspnMap(raw) {
  const rows = arr(obj(arr(obj(arr(obj(raw).sports)[0]).leagues)[0]).teams)
    .map((r) => obj(obj(r).team));
  if (!rows.length) throw new Error('team list has no teams');
  const claims = new Map();
  const unmatched = [];
  for (const t of rows) {
    const espnId = str(t.id, 12);
    if (!/^\d{1,8}$/.test(espnId)) continue;
    const teamId = live.resolveEspnTeam({
      displayName: str(t.displayName, 60), location: str(t.location, 60),
      shortDisplayName: str(t.shortDisplayName, 60), name: str(t.name, 40),
    });
    if (!teamId) { unmatched.push(`${espnId} ${str(t.displayName, 60)}`); continue; }
    if (!claims.has(teamId)) claims.set(teamId, new Set());
    claims.get(teamId).add(espnId);
  }
  const map = {};
  const conflicts = [];
  for (const t of teams.TEAMS) {
    const ids = claims.get(t.id);
    if (ids && ids.size === 1) map[t.id] = [...ids][0];
    else if (ids && ids.size > 1) conflicts.push(`${t.id}: ${[...ids].join(', ')}`);
  }
  const missing = teams.TEAMS.map((t) => t.id).filter((id) => !map[id]);
  return { map, missing, unmatched, conflicts };
}

/* ------------------------------------------------------------------ *
 * A team's schedule
 * ------------------------------------------------------------------ */

/** Scoreboard scores are strings, schedule scores are {value, displayValue}. */
function score(v) {
  if (v && typeof v === 'object') return int(v.displayValue !== undefined ? v.displayValue : v.value, 0, 250);
  return int(v, 0, 250);
}

function tvOf(comp) {
  const out = [];
  for (const b of arr(comp.broadcasts).slice(0, 4)) {
    const o = obj(b);
    const names = [str(obj(o.media).shortName, 16), ...arr(o.names).slice(0, 3).map((n) => str(n, 16))];
    for (const n of names) if (n && !out.includes(n)) out.push(n);
  }
  return out.slice(0, 2).join(' / ');
}

function recordOf(c, type) {
  const r = arr(c.record || c.records).map(obj).find((x) => str(x.type, 20) === type);
  const s = r ? str(r.displayValue || r.summary, 12) : '';
  return /^\d{1,2}-\d{1,2}(-\d{1,2})?$/.test(s) ? s : '';
}

/** One schedule event -> a row, or null when it cannot be read. */
function scheduleRow(raw, espnId) {
  const ev = obj(raw);
  const id = str(ev.id, 20);
  if (!/^\d{1,20}$/.test(id)) return null;
  const comp = obj(arr(ev.competitions)[0]);
  const cs = arr(comp.competitors).map(obj);
  if (cs.length !== 2) return null;
  const usRaw = cs.find((c) => str(c.id, 12) === espnId || str(obj(c.team).id, 12) === espnId);
  const themRaw = cs.find((c) => c !== usRaw);
  if (!usRaw || !themRaw) return null;
  const date = isoOrEmpty(comp.date || ev.date);
  if (!date) return null;
  const status = obj(Object.keys(obj(comp.status)).length ? comp.status : ev.status);
  const state = gameState(status) || 'pre';
  const opp = espnTeam(themRaw.team);
  const neutral = comp.neutralSite === true;
  const loc = neutral ? 'neutral' : str(usRaw.homeAway, 6) === 'away' ? 'away' : 'home';
  const timeValid = !(ev.timeValid === false || comp.timeValid === false);

  const final = state === 'final';
  const live2 = state === 'in' || state === 'half';
  let us = score(usRaw.score);
  let them = score(themRaw.score);
  if (!(final || live2) || us === null || them === null) { us = null; them = null; }
  let outcome = '';
  if (final && us !== null) {
    outcome = usRaw.winner === true ? 'W' : themRaw.winner === true ? 'L' : us > them ? 'W' : us < them ? 'L' : 'T';
  }
  const result = final && us !== null ? `${outcome} ${us}-${them}`
    : state === 'postponed' ? 'Postponed' : state === 'canceled' ? 'Canceled' : '';
  const oppRank = int(obj(themRaw.curatedRank).current, 1, 25);

  return {
    id,
    date,
    wk: WK_FMT.format(Date.parse(date)),
    opp: (loc === 'away' ? 'at ' : loc === 'neutral' ? 'vs ' : '') + opp.name,
    oppName: opp.name,
    oppTeamId: opp.teamId,
    oppEspnId: opp.espnId,
    oppRank,
    loc,
    state,
    final,
    live: live2,
    result,
    outcome,
    liveScore: live2 && us !== null ? `${us}-${them}` : '',
    detail: live2 ? str(obj(status.type).shortDetail || obj(status.type).detail, 40) : '',
    conf: comp.conferenceCompetition === true,
    confKnown: typeof comp.conferenceCompetition === 'boolean',
    ranked: oppRank !== null,
    rivalry: false,
    current: false,
    kickoffISO: timeValid ? date : '',
    kickoffLabel: kickoffLabel(date, timeValid),
    tv: tvOf(comp),
    espnRank: int(obj(usRaw.curatedRank).current, 1, 25),
    confRecordHint: recordOf(usRaw, 'vsconf'),
  };
}

const fmtRecord = (w, l, t) => `${w}-${l}${t ? `-${t}` : ''}`;

/**
 * ESPN's schedule response -> a team's facts. Throws when the response is not
 * for the team asked about - one wrong id in espn-ids.js must show nothing,
 * never someone else's season.
 */
function normaliseSchedule(raw, teamId, nowMs) {
  const espnId = espnIdFor(teamId);
  if (!espnId) throw new Error(`no ESPN id for ${teamId}`);
  const body = obj(raw);
  const who = espnTeam(body.team);
  if (who.espnId !== espnId || (who.teamId && who.teamId !== teamId)) {
    throw new Error(`schedule for ${teamId} came back as ${who.espnId} ${who.name}`);
  }
  if (!Array.isArray(body.events)) throw new Error('schedule has no events list');

  const seen = new Set();
  const rows = [];
  for (const e of body.events.slice(0, MAX_EVENTS)) {
    const r = scheduleRow(e, espnId);
    if (r && !seen.has(r.id)) { seen.add(r.id); rows.push(r); }
  }
  rows.sort((a, b) => Date.parse(a.date) - Date.parse(b.date));
  if (!rows.length) throw new Error('schedule has no readable games');

  let w = 0, l = 0, t = 0, cw = 0, cl = 0, ct = 0;
  for (const r of rows) {
    if (!r.outcome) continue;
    if (r.outcome === 'W') w++; else if (r.outcome === 'L') l++; else t++;
    if (r.conf) { if (r.outcome === 'W') cw++; else if (r.outcome === 'L') cl++; else ct++; }
  }
  const finals = rows.filter((r) => r.outcome);
  // Conference record: counted from the games when ESPN flags conference
  // games, otherwise ESPN's own vs-conference split on the latest final.
  const confKnown = rows.some((r) => r.confKnown);
  const lastFinal = finals[finals.length - 1] || null;
  const confRecord = confKnown ? fmtRecord(cw, cl, ct) : (lastFinal ? lastFinal.confRecordHint : '');

  // This week's game: one in progress, else the next one not yet played.
  const upcoming = rows.filter((r) => r.live || (r.state === 'pre' || r.state === 'delayed'));
  const current = upcoming[0] || null;
  if (current) current.current = true;
  const espnRank = (current && current.espnRank) || (lastFinal && lastFinal.espnRank) || null;

  return {
    teamId,
    espnId,
    season: seasonFor(nowMs),
    record: fmtRecord(w, l, t),
    confRecord,
    espnRank,
    schedule: rows.map(({ confKnown: _k, confRecordHint: _h, espnRank: _r, ...row }) => row),
    nextGame: current ? {
      eventId: current.id,
      opponent: current.opp,
      oppName: current.oppName,
      oppRank: current.oppRank,
      loc: current.loc,
      kickoffISO: current.kickoffISO,
      kickoffLabel: current.kickoffLabel,
      tv: current.tv,
      state: current.state,
      live: current.live,
      liveScore: current.liveScore,
      detail: current.detail,
    } : null,
    lastGame: lastFinal ? { eventId: lastFinal.id, oppName: lastFinal.oppName, result: lastFinal.result, date: lastFinal.date } : null,
  };
}

/* ------------------------------------------------------------------ *
 * The poll
 * ------------------------------------------------------------------ */

/** ESPN's /rankings -> the AP Top 25, or a throw. Only the AP poll: the
 *  coaches' poll and the CFP ranking are different lists, and mixing them is
 *  how a team ends up #2 on one screen and #1 on the next. */
function normalisePoll(raw) {
  const polls = arr(obj(raw).rankings).map(obj);
  const ap = polls.find((p) => str(p.type, 12).toLowerCase() === 'ap')
    || polls.find((p) => /^ap\b/i.test(str(p.name, 40)) || /^ap\b/i.test(str(p.shortName, 40)));
  if (!ap) throw new Error('no AP poll in the rankings');
  const seenRank = new Set();
  const seenTeam = new Set();
  const ranks = [];
  for (const r of arr(ap.ranks).slice(0, 40).map(obj)) {
    const rank = int(r.current, 1, 25);
    if (rank === null || seenRank.has(rank)) continue;
    const t = espnTeam(r.team);
    if (!t.espnId || seenTeam.has(t.espnId)) continue;
    seenRank.add(rank);
    seenTeam.add(t.espnId);
    const rec = str(obj(r.record).summary || r.recordSummary, 12);
    ranks.push({
      rank,
      espnId: t.espnId,
      teamId: t.teamId,
      team: t.name,
      record: /^\d{1,2}-\d{1,2}(-\d{1,2})?$/.test(rec) ? rec : '',
      previous: int(r.previous, 1, 25),
    });
  }
  ranks.sort((a, b) => a.rank - b.rank);
  if (ranks.length < 10) throw new Error(`AP poll has only ${ranks.length} readable rows`);
  const occ = obj(ap.occurrence);
  return {
    name: 'AP Top 25',
    week: str(occ.displayValue, 30),
    date: isoOrEmpty(ap.date) || isoOrEmpty(ap.lastUpdated),
    ranks,
  };
}

function pollRankOf(poll, espnId) {
  if (!poll || !espnId) return null;
  const hit = poll.ranks.find((r) => r.espnId === espnId);
  return hit ? hit.rank : null;
}

/**
 * The ticker's ranks, from the same poll as the team page. The scoreboard's
 * own curatedRank is ESPN's too, but it moves to the CFP ranking in November
 * while the team page reads the AP poll - and a team shown #4 on the ticker
 * and #6 on its own page is a bug report. With a poll in hand, the poll wins,
 * both ways: a team the poll does not rank is unranked here as well.
 */
function applyPollRanks(result, poll) {
  if (!poll || !result || !result.available) return result;
  const side = (s) => ({ ...s, rank: pollRankOf(poll, s.espnId) });
  const game = (g) => ({ ...g, away: side(g.away), home: side(g.home) });
  return { ...result, games: arr(result.games).map(game), all: arr(result.all).map(game), rankSource: poll.name };
}

/* ------------------------------------------------------------------ *
 * The board's Top 25, from the poll
 * ------------------------------------------------------------------ */

const STATE_PRIORITY = { in: 0, half: 0, delayed: 1, pre: 1, final: 2, postponed: 3, canceled: 3 };

/** The game this week a ranked team is in: live, else the next, else the
 *  last one played. */
function gameFor(espnId, allGames, nowMs) {
  const mine = arr(allGames).filter((g) => g.away.espnId === espnId || g.home.espnId === espnId);
  if (!mine.length) return null;
  return mine.slice().sort((a, b) => (STATE_PRIORITY[a.state] ?? 4) - (STATE_PRIORITY[b.state] ?? 4)
    || (a.state === 'final'
      ? Date.parse(b.startsAt || 0) - Date.parse(a.startsAt || 0)
      : Date.parse(a.startsAt || 0) - Date.parse(b.startsAt || 0)))[0];
}

/**
 * The poll -> rows in the board's `rankings` shape, each with its game this
 * week from the scoreboard. `haveGames` false means the scoreboard could not
 * be read: then an empty game is "not known", not a bye, and the page says so.
 */
function pollRows(poll, allGames, nowMs) {
  return poll.ranks.map((r) => {
    const g = gameFor(r.espnId, allGames, nowMs);
    if (!g) return { rank: r.rank, team: r.team, record: r.record, game: '', time: '', line: '', gameId: '' };
    const home = g.home.espnId === r.espnId;
    const us = home ? g.home : g.away;
    const them = home ? g.away : g.home;
    const oppRank = pollRankOf(poll, them.espnId);
    const opp = (oppRank ? `#${oppRank} ` : '') + them.name;
    const game = (g.neutral ? 'vs ' : home ? 'vs ' : 'at ') + opp;
    let time = '';
    if (g.final && us.score !== null) {
      const o = us.score > them.score ? 'W' : us.score < them.score ? 'L' : 'T';
      time = `Final · ${o} ${us.score}-${them.score}`;
    } else if (g.live && us.score !== null) {
      time = `Live · ${us.score}-${them.score}${g.detail ? ` · ${g.detail}` : ''}`;
    } else if (g.state === 'postponed' || g.state === 'canceled') {
      time = g.state === 'postponed' ? 'Postponed' : 'Canceled';
    } else if (g.startsAt) {
      time = [kickoffLabel(g.startsAt, true), g.tv && g.tv.length ? g.tv[0] : ''].filter(Boolean).join(' · ');
    }
    return {
      rank: r.rank, team: r.team, record: r.record, game, time,
      line: g.state === 'pre' ? str(g.line, 40) : '',
      gameId: '',
      dkUrl: g.dkUrl || '',
    };
  });
}

/** True when the board's own Top 25 should give way to the poll: it has none,
 *  or it was built before the latest poll came out. */
function boardNeedsPoll(boardDoc, poll) {
  if (!poll) return false;
  if (!arr(boardDoc && boardDoc.rankings).length) return true;
  const built = Date.parse((boardDoc && boardDoc.generatedAt) || '');
  const released = Date.parse(poll.date || '');
  return Number.isFinite(released) && (!Number.isFinite(built) || built < released);
}

/* ------------------------------------------------------------------ *
 * Facts over a stored page
 * ------------------------------------------------------------------ */

/** "the Arkansas game", "the Arkansas and Oklahoma games", "the last 3 games". */
function gamesPhrase(names) {
  if (names.length === 1) return `the ${names[0]} game`;
  if (names.length === 2) return `the ${names[0]} and ${names[1]} games`;
  return `the last ${names.length} games`;
}

/** Finished games that ended after `writtenAt`. */
function playedSince(facts, writtenAt) {
  const w = Date.parse(writtenAt || '');
  if (!facts || !Number.isFinite(w)) return [];
  return facts.schedule.filter((r) => r.final && Date.parse(r.date) + GAME_LENGTH_MS > w);
}

/**
 * The page a reader sees: the stored model page (or none) with the facts laid
 * over it. Facts win on record, conference record, rank, schedule and the
 * next game; the model keeps its storyline (dated, and flagged when a game has
 * been played since), its betting line for the next game when it is still the
 * same game, and its rivalry flags.
 *
 * `page` is the stored fan/<id> document or null; `facts` and `poll` are this
 * module's shapes or null. With no facts, the page is returned as it was.
 */
function overlay(page, facts, poll, { teamId, meta, nowMs = Date.now() } = {}) {
  const base = page ? { ...page } : {};
  const out = { ...base, team: teamId, meta, researched: !!page };
  if (!facts) return { ...out, facts: null };

  const modelRows = arr(base.schedule);
  const rivalryWith = new Set(modelRows.filter((r) => r && r.rivalry).map((r) => oppTeamId(r.opp)).filter(Boolean));
  const schedule = facts.schedule.map((r) => {
    const rank = poll ? pollRankOf(poll, r.oppEspnId) : r.oppRank;
    return {
      wk: r.wk, opp: r.opp, loc: r.loc, result: r.result,
      outcome: r.outcome, live: r.live, liveScore: r.liveScore,
      current: r.current, ranked: rank !== null, oppRank: rank,
      rivalry: !!(r.oppTeamId && rivalryWith.has(r.oppTeamId)),
      date: r.date,
    };
  });

  let nextGame = null;
  if (facts.nextGame) {
    const n = facts.nextGame;
    const m = base.nextGame || null;
    // The model's line and board link belong to one game. Kept only while the
    // next game is still that game.
    const nRow = facts.schedule.find((r) => r.id === n.eventId);
    const same = m && nRow && nRow.oppTeamId && oppTeamId(m.opponent) === nRow.oppTeamId;
    const oppRank = poll ? pollRankOf(poll, nRow && nRow.oppEspnId) : n.oppRank;
    nextGame = {
      opponent: n.opponent, oppRank, kickoffISO: n.kickoffISO, kickoffLabel: n.kickoffLabel,
      tv: n.tv, live: n.live, liveScore: n.liveScore, detail: n.detail,
      line: same ? m.line || '' : '', gameId: same ? m.gameId || '' : '',
    };
  }

  const rankNum = poll ? pollRankOf(poll, facts.espnId) : facts.espnRank;
  const since = page ? playedSince(facts, base.lastChecked) : [];
  return {
    ...out,
    rank: rankNum ? `#${rankNum}` : '',
    record: facts.record,
    confRecord: facts.confRecord,
    secRecord: undefined,
    nextGame,
    schedule,
    lastGame: facts.lastGame,
    storylineAsOf: page ? base.lastChecked || '' : '',
    storylineNote: since.length ? `Written before ${gamesPhrase(since.map((r) => r.oppName))} — refresh for a new take` : '',
    storylineStale: since.length > 0,
    facts: {
      source: 'ESPN',
      fetchedAt: facts.fetchedAt || '',
      stale: !!facts.stale,
      rankSource: poll ? `${poll.name}${poll.week ? `, ${poll.week}` : ''}` : (rankNum ? 'ESPN' : ''),
    },
  };
}

/* ------------------------------------------------------------------ *
 * Fetching, cached
 * ------------------------------------------------------------------ */

function fetchJson(fetchImpl, url, timeoutMs) {
  return live.fetchEspnJson(fetchImpl, url, timeoutMs, MAX_BYTES);
}

/**
 * `facts(teamId)` and `poll()` each resolve to their shape plus `fetchedAt`
 * and `stale`, or null, and never reject.
 *
 * Order of preference: fresh memory; fresh Firestore (a cold instance); a
 * fetch; on failure the last good copy from either, marked stale. Concurrent
 * callers for one key share one fetch.
 */
function createTeamFacts({ fetch: fetchImpl, db = null, now = Date.now, log = console,
  ttlMs = TTL_MS, failTtlMs = FAIL_TTL_MS, timeoutMs = FETCH_TIMEOUT_MS } = {}) {
  const slots = new Map();
  let upstreamCalls = 0;

  function slot(key) {
    if (!slots.has(key)) slots.set(key, { good: null, failAt: 0, inflight: null, storeRead: false });
    return slots.get(key);
  }

  const fresh = (s) => s.good && now() - s.good.at < ttlMs;
  const serve = (s, stale) => (s.good ? { ...s.good.value, fetchedAt: new Date(s.good.at).toISOString(), stale } : null);

  async function cached(key, ref, load) {
    const s = slot(key);
    if (fresh(s)) return serve(s, false);
    if (!s.good && !s.storeRead && ref) {
      s.storeRead = true;
      try {
        const doc = await ref.get();
        const v = doc.exists ? doc.data() : null;
        const at = v ? Date.parse(v.fetchedAt || '') : NaN;
        if (v && Number.isFinite(at) && !s.good) {
          const { fetchedAt: _f, stale: _s, ...value } = v;
          s.good = { value, at };
        }
      } catch (err) {
        log.error(`[teamfacts] store read ${key} failed:`, err && err.message ? err.message : err);
      }
      if (fresh(s)) return serve(s, false);
    }
    if (s.failAt && now() - s.failAt < failTtlMs) return serve(s, true);
    if (!s.inflight) {
      s.inflight = (async () => {
        upstreamCalls++;
        try {
          const value = await load();
          s.good = { value, at: now() };
          s.failAt = 0;
          if (ref) {
            await ref.set({ ...value, fetchedAt: new Date(s.good.at).toISOString() })
              .catch((err) => log.error(`[teamfacts] store write ${key} failed:`, err && err.message ? err.message : err));
          }
          return serve(s, false);
        } catch (err) {
          s.failAt = now();
          log.error(`[teamfacts] ${key} fetch failed:`, err && err.message ? err.message : err);
          return serve(s, true);
        }
      })().finally(() => { s.inflight = null; });
    }
    return s.inflight;
  }

  async function facts(teamIdRaw) {
    // The only door to Firestore for a team id, as everywhere else.
    const teamId = teams.validId(teamIdRaw);
    const espnId = teamId ? ESPN_IDS[teamId] : null;
    if (!teamId || !espnId) return null;
    const ref = db ? db.collection('teamfacts').doc(teamId) : null;
    return cached(`team:${teamId}`, ref, async () => {
      const raw = await fetchJson(fetchImpl, scheduleUrl(espnId, seasonFor(now())), timeoutMs);
      return normaliseSchedule(raw, teamId, now());
    });
  }

  async function poll() {
    const ref = db ? db.collection('polls').doc('ap') : null;
    return cached('poll:ap', ref, async () => normalisePoll(await fetchJson(fetchImpl, RANKINGS_URL, timeoutMs)));
  }

  return { facts, poll, stats: () => ({ upstreamCalls }) };
}

module.exports = {
  ESPN_BASE, TEAMS_URL, RANKINGS_URL, scheduleUrl, TTL_MS, FAIL_TTL_MS,
  ESPN_IDS, UNMAPPED, espnIdFor, seasonFor, kickoffLabel, oppTeamId,
  buildEspnMap, normaliseSchedule, normalisePoll, pollRankOf, applyPollRanks,
  pollRows, boardNeedsPoll, gamesPhrase, playedSince, overlay, createTeamFacts,
};

/* ------------------------------------------------------------------ *
 * Regenerating espn-ids.js
 *
 *   curl -s 'https://site.web.api.espn.com/apis/site/v2/sports/football/college-football/teams?groups=80&limit=500' > /tmp/teams.json
 *   node teamfacts.js --ids /tmp/teams.json > espn-ids.js
 *
 * Every teams.js id must map to exactly one ESPN team; any that does not is
 * written into UNMAPPED, where the test suite will ask about it.
 *
 * CAREFUL: /teams ignores groups=80 and returns every division, truncated at
 * `limit`. On 2026-09-26 its 500 omitted 15 FBS teams, which would land in
 * UNMAPPED here. Every id in espn-ids.js was checked against ESPN that day
 * (the missing 15 at /teams/<id>); do not drop one because a regenerate lost it.
 * ------------------------------------------------------------------ */
if (require.main === module && process.argv[2] === '--ids' && process.argv[3]) {
  const raw = JSON.parse(require('fs').readFileSync(process.argv[3], 'utf8'));
  const { map, missing, unmatched, conflicts } = buildEspnMap(raw);
  const lines = teams.TEAMS.filter((t) => map[t.id]).map((t) => `  ${JSON.stringify(t.id)}: ${JSON.stringify(map[t.id])},`);
  process.stdout.write([
    '/**',
    ' * teams.js id -> ESPN team id. GENERATED - do not edit by hand:',
    ' *   node teamfacts.js --ids <ESPN /teams?groups=80&limit=500 response> > espn-ids.js',
    ' *',
    ' * UNMAPPED lists every teams.js id with no single ESPN match. Those teams show',
    ' * the model\'s page with no facts laid over it. test/teamfacts.js holds this',
    ' * file to "every team maps to exactly one ESPN id, or is listed here".',
    ' */',
    '',
    'const ESPN_IDS = {',
    ...lines,
    '};',
    '',
    `const UNMAPPED = ${JSON.stringify(missing)};`,
    '',
    'module.exports = { ESPN_IDS, UNMAPPED };',
    '',
  ].join('\n'));
  if (conflicts.length) process.stderr.write(`conflicts: ${conflicts.join('; ')}\n`);
  if (unmatched.length) process.stderr.write(`ESPN teams matching no teams.js id: ${unmatched.join('; ')}\n`);
}
